//
//  TableMacroTests.swift
//  Squeal
//
//  Created by Sacha Durand Saint Omer on 07/03/2026.
//

import Testing
import Foundation
import Squeal

// Declare a table using the @Table macro
@Table(schema: "products")
struct Products {
    let id: UUID
    let name: String
    let price: Double
    let description: String?
}

struct TableMacroTests {

    @Test
    func macroGeneratesTableStruct() {
        // ProductsTable should be generated by the macro
        let products = ProductsTable()
        #expect(ProductsTable.schema == "products")
        _ = products // silence unused warning
    }

    @Test
    func macroSELECTall() {
        let products = ProductsTable()
        let query = SQL
            .SELECT(*)
            .FROM(products)
        #expect("\(query)" == "SELECT * FROM products")
    }

    @Test
    func macroSELECTcolumns() {
        let products = ProductsTable()
        let query = SQL
            .SELECT(products.id, products.name, products.price)
            .FROM(products)
        #expect("\(query)" == "SELECT products.id, products.name, products.price FROM products")
    }

    @Test
    func macroWHERE() {
        let products = ProductsTable()
        let query = SQL
            .SELECT(products.name)
            .FROM(products)
            .WHERE(\.price > 9.99)
        #expect(query.parameters.count == 1)
        #expect(query.query == "SELECT products.name FROM products WHERE price > $1")
    }

    @Test
    func macroSELECTKeyPath() {
        let query = TSQL<ProductsTable>
            .SELECT(\.id, \.name)
            .FROM(ProductsTable())
        #expect("\(query)" == "SELECT id, name FROM products")
    }
}
